apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: website
          image: yoerivd/service
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
            requests:
              memory: '1Mi'
              cpu: '1m'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-service
  ports:
    - port: 80
      targetPort: 80
